apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: abril21/k8spersonas-front:latest  # Replace with your actual image
        ports:
        - containerPort: 5173 
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "350m"