# Configuración Global
nameOverride: ""
fullnameOverride: ""
# Configuración de Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""
  automount: true
apiVersion: v1
app:
  name: api
  image: joseph888/apinombres
  replicas: 1
  env:
    URLMONGO: "mongodb://admin:admin@{{ include \"my-helm-chart.fullname\" . }}-mongodb-service:27017/personas?authSource=admin"
api:
  service:
    targetPort: 8080
  resources:
    requests:
      cpu: "10m"
    limits:
      cpu: "350m"
front:
  name: front
  image: abril21/k8spersonas-front:latest
  replicas: 1
  port: 5173
  resources:
    requests:
      cpu: "50m"
    limits:
      cpu: "350m"
mongodb:
  name: mongodb
  image: mongo:latest
  replicas: 1
  env:
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: admin
    MONGO_INITDB_DATABASE: personas
  storage:
    size: 5Gi
  resources:
    requests:
      cpu: "50m"
    limits:
      cpu: "350m"
hpa:
  minReplicas: 1
  maxReplicas: 4
  averageUtilization: 75
ingress:
  enabled: true
  apiPath: /backend(/|$)(.*)
  frontPath: /front(/|$)(.*)
image:
  tag: d2e6e3e5807c14a1d5d54b0ff955b71cc1c3c22b
