apiVersion: v1
entries:
  my-helm-chart2:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-02-25T12:24:54.224161221Z"
    description: A Helm chart for deploying a full-stack application with API, frontend,
      and MongoDB.
    digest: 9d8202dad7672e3ed026327322f89f7879cd3cd3b85d44438c7a551d607dd48e
    name: my-helm-chart2
    urls:
    - https://joseph8884.github.io/ManifestsApiNombres/charts/my-helm-chart2-0.2.6.tgz
    version: 0.2.6
generated: "2025-02-25T12:24:54.223467445Z"
