apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-helm-chart2.fullname" . }}-api-nombres
  labels:
    app: apiprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiprod
  template:
    metadata:
      labels:
        app: apiprod
    spec:
      containers:
      - name: apiprod
        image: {{ .Values.app.image }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080  # Update with your app's port
        env:
        - name: URLMONGO
          value: 'mongodb://admin:admin@{{ include "my-helm-chart2.fullname" . }}-mongodb-service:27017/personas?authSource=admin'
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "350m"