apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-helm-chart2.fullname" . }}-ingress
  namespace: produccion
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx  # Asegúrate que coincida con tu controlador
  rules:
    http:
      paths:
      - path: /backend(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "my-helm-chart2.fullname" . }}-api-service
            port:
              number: 80
      - path: /front(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "my-helm-chart2.fullname" . }}-front-service
            port:
              number: 80