apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-chart2.fullname" . }}-mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP